# Generated by Django 4.1.5 on 2023-02-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(default='Unspecified!', max_length=64),
        ),
    ]
