# Generated by Django 4.1.5 on 2023-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
