# Generated by Django 4.1.5 on 2023-02-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_comment_listing_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listing'),
        ),
    ]
