# Generated by Django 4.1.6 on 2023-02-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listing'),
        ),
    ]
